import complemented_lattices_orthocomplemented_lattices_posets_theorem_canonical_lane_mathlib.GateLemmas
import complemented_lattices_orthocomplemented_lattices_posets_theorem_canonical_lane_mathlib.FinalTheorem
